// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prefer a direct (non-pooled) connection for migrations when available —
// pooled/pgbouncer connections (e.g. Vercel's POSTGRES_PRISMA_URL) don't
// reliably support the advisory locks Prisma Migrate needs.
const migrationUrl =
  process.env["DATABASE_URL"] ??
  process.env["POSTGRES_URL_NON_POOLING"] ??
  process.env["POSTGRES_PRISMA_URL"] ??
  process.env["POSTGRES_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: migrationUrl,
  },
});
