// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolveMigrationUrl } from "./src/lib/database-url";

// Prefer a direct (non-pooled) connection for migrations when available —
// pooled/pgbouncer connections (e.g. Neon's DATABASE_URL, Vercel's
// POSTGRES_PRISMA_URL) don't reliably support the advisory locks Prisma
// Migrate needs.
//
// This is the dangerous one to get wrong: `vercel-build` runs
// `prisma migrate deploy`, so on a Preview deployment this must resolve to
// the staging Neon branch or a test build would migrate the live database.
const migrationUrl = resolveMigrationUrl();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: migrationUrl,
  },
});
